name: ci-mac
on:   [push]
jobs:
    ci:
        runs-on: macos-15
        strategy:
            matrix:
                run-config:
                    - { scheme: 'SwiftXISF', configuration: 'Debug',   project: 'SwiftXISF.xcodeproj', build: 1, analyze: 1, test: 1, info: 1, destination: 'platform=macOS' }
                    - { scheme: 'SwiftXISF', configuration: 'Release', project: 'SwiftXISF.xcodeproj', build: 1, analyze: 1, test: 0, info: 1, destination: 'platform=macOS' }
        steps:
            
            - uses: actions/checkout@v6
              with:
                submodules: 'recursive'
                
            - uses: macmade/action-xcodebuild@v1.0.0

    spm:
        runs-on: macos-15
        strategy:
            matrix:
                configuration: [ 'debug', 'release' ]
        steps:

            - uses: actions/checkout@v6
              with:
                submodules: 'recursive'

            - name: Build
              run: swift build --configuration ${{ matrix.configuration }}

            - name: Test
              run: swift test --configuration ${{ matrix.configuration }}
